RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 300
CHUNK_OVERLAP: 30
DATA_PATH: 'data/'
DB_FAISS_PATH: 'vectorstore/chroma'
MODEL_TYPE: 'mistral'
MODEL_BIN_PATH: 'models/mistral-7b-instruct-v0.1.Q5_K_M.gguf'
EMBEDDINGS: 'sentence-transformers/all-mpnet-base-v2'
MAX_NEW_TOKENS: 2048
TEMPERATURE: 0.00
